### ISSUE TITLE
PaymentIntentService Create - Unexpected character encountered while parsing value

### ISSUE THREAD

**Issue by EmaginationStore** [stripe/stripe-dotnet#1507]
I am trying to create a payment intent, using version 22.8.1.

My code is as follows:

```c#
StripeConfiguration.SetApiKey("secretKey");
var paymentIntents = new PaymentIntentService();
var createOptions = new PaymentIntentCreateOptions
 {
    Amount = 1499,
    Currency = "gbp",
    AllowedSourceTypes = new List<string> { "card" }
};
var intent = paymentIntents.Create(createOptions);
```

This produces the error: Unexpected character encountered while parsing value

**Comment by ob-stripe** [comment]
Hi @EmaginationStore, can you share the full stack trace?

**Comment by EmaginationStore** [comment]
Hi, please see below:  

 at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Stripe.Mapper`1.MapFromJson(String json, String parentToken, StripeResponse stripeResponse)
   at Stripe.Infrastructure.Requestor.BuildStripeException(StripeResponse response, HttpStatusCode statusCode, String requestUri, String responseContent)
   at Stripe.Infrastructure.Requestor.ExecuteRequest(HttpRequestMessage requestMessage)
   at Stripe.Infrastructure.Requestor.PostString(String url, RequestOptions requestOptions)
   at Stripe.Service`1.PostRequest[T](String url, BaseOptions options, RequestOptions requestOptions)
   at Stripe.PaymentIntentService.Create(PaymentIntentCreateOptions options, RequestOptions requestOptions)

**Comment by ob-stripe** [comment]
Hm, strange. It looks like you're getting an error response that isn't valid JSON. Is there maybe a corporate proxy or firewall between your server and Stripe's API servers that could alter HTTP requests?

**Comment by EmaginationStore** [comment]
Hi, I tried running the code from home over the weekend to avoid our corporate firewall and I received the same error message.

**Comment by ob-stripe** [comment]
Alright, thanks. Unfortunately I can't seem to reproduce this on my end. Could you log into your Stripe account and send a message to Stripe's support using the form at https://support.stripe.com/email, briefly explain the problem and point to this GitHub issue? Please also include timestamps for the times you sent those payment intent creation requests. This way we will be able to check our internal logs and see what's the error that's causing the JSON deserialization issue.

**Comment by EmaginationStore** [comment]
Hi, I have managed to resolve the issue I was having, my fault! There was a linefeed character at the end of the secret key ('\n'). This was causing an invalid Json error.

It might be worth adding a check in the library for invalid characters.

**Comment by ob-stripe** [comment]
Hi @EmaginationStore, thanks for this information!

I'll leave this issue open for now, as I think there are a few improvements we can make in the client library:
- checking for invalid characters in API keys, as you mentioned
- returning a clearer exception message when receiving non-JSON responses

**Comment by ob-stripe** [comment]
As of v27.0.0, the library will now return clearer error messages for invalid API keys (empty string or containing whitespace characters) as well as non-JSON responses from the server.
