### ISSUE TITLE
Unknown parameter when using PaymentIntents and TransferData

### ISSUE THREAD

**Issue by jlnostr** [stripe/stripe-dotnet#1540]
Hello there,
the following code is failing on the current API version (24.0.2, .NET Core 2.2, Windows 10).

```csharp

var service = new PaymentIntentService("sk_test_...");
var intent = await service.CreateAsync(new PaymentIntentCreateOptions
{
    Amount             = 1000,
    Currency           = "EUR",
    TransferGroup      = "<unique-string>",
    OnBehalfOf         = "acct_...",
    PaymentMethodTypes = new List<string> {"card"},
    TransferData = new PaymentIntentTransferDataOptions
    {
        Amount      = 900,
        Destination = "acct_..."
    }
});

```

with the following exception:

```
Stripe.StripeException: Received unknown parameter: transfer_data[amount]
   at Stripe.Infrastructure.Requestor.ExecuteRequestAsync(HttpRequestMessage requestMessage, CancellationToken cancellationToken) in /_/src/Stripe.net/Infrastructure/Requestor.cs:line 118
   at Stripe.Service`1.PostRequestAsync[T](String url, BaseOptions options, RequestOptions requestOptions, CancellationToken cancellationToken) in /_/src/Stripe.net/Services/Service.cs:line 148
```

**Comment by remi-stripe** [comment]
@jlnostr This is expected. `transfer_data[amount]` is currently not accessible publicly and supported only for historical reasons. We recommend that you instead use Application Fees when you want to take a fee for your platform. Pass `ApplicationFeeAmount` instead.
