### ISSUE TITLE
Event processing api version 2019-03-14

### ISSUE THREAD

**Issue by mvanhalen** [stripe/stripe-dotnet#1579]
Running .Net Core 2.2 when processing Stripe events I can this error with the EventUtility.ParseEvent and  EventService  service.get. Happens when I parse the received json as a string or get the json from the EventService.

```
{Newtonsoft.Json.JsonSerializationException: Error converting value "pi_1EPBRz2mm1NVm9AtFJVLBXOh" to type 'Stripe.PaymentIntent'. Path 'payment_intent', line 88, position 53. ---> System.ArgumentException: Could not cast or convert from System.String to Stripe.PaymentIntent.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType) in /_/Src/Newtonsoft.Json/Utilities/ConvertUtils.cs:line 616
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType) in /_/Src/Newtonsoft.Json/Utilities/ConvertUtils.cs:line 587
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 982
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 989
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 1032
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 2386
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 114
   at Stripe.Infrastructure.StripeObjectConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /_/src/Stripe.net/Infrastructure/JsonConverters/StripeObjectConverter.cs:line 65
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 2159
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 1032
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 2386
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 485
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 1032
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 2386
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 114
   at Stripe.Infrastructure.EventConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /_/src/Stripe.net/Infrastructure/JsonConverters/EventConverter.cs:line 74
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 2159
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 163
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) in /_/Src/Newtonsoft.Json/JsonSerializer.cs:line 907
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) in /_/Src/Newtonsoft.Json/JsonConvert.cs:line 828
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings) in /_/Src/Newtonsoft.Json/JsonConvert.cs:line 786
   at Stripe.Mapper`1.MapFromJson(String json, String parentToken, StripeResponse stripeResponse) in /_/src/Stripe.net/Infrastructure/Public/Mapper.cs:line 31
   at Stripe.EventService.Get(String eventId, RequestOptions requestOptions) in /_/src/Stripe.net/Services/Events/EventService.cs:line 25
   at UnitTests.Event.StripeMissedEvent() in C:\Users\mvanh\Source\Repos\iGenDash.Core\UnitTests\Event.cs:line 85}
```

By using the NewtonSoft JsonConvert options direcly I can make it work ignoring the error. Might help somebody so this code works when you get the json of the event as a string on your webserver. But this is not a solution.

```c#
Stripe.Event ev = JsonConvert.DeserializeObject<Stripe.Event>(json,
                    new JsonSerializerSettings
                    {
                        Error = delegate (object sender, Newtonsoft.Json.Serialization.ErrorEventArgs args)
                        {
                            args.ErrorContext.Handled = true;
                        }

                    });
```

Probably the new api does something which is different regarding to the PaymentIntent.

Was with the lastest Stripe packge from nuget. And it´s recurring billing transaction.

**Comment by remi-stripe** [comment]
@mvanhalen Thanks a lot for the report! In theory, `payment_intent` should always be the full `PaymentIntent` object on the `Invoice` resource but in this case it looks like we are sending the id only instead.

I'll push a fix and we can release a new version tomorrow.

**Comment by mvanhalen** [comment]
@remi-stripe no problem. This package saved me so much time. Was time to do something back.

**Comment by remi-stripe** [comment]
@mvanhalen I just release 25.7.0 where `payment_intent` can now be a string or a full object. We're also making changes to the resource so that it's a string by default moving forward and you have to explicitly expand it otherwise.

Make sure to upgrade to that version!
