### ISSUE TITLE
Invalid UTF-8 characters after upgrade to 27.0

### ISSUE THREAD

**Issue by bgecawichBAO** [stripe/stripe-dotnet#1654]
Team:

I have upgraded from version 26.0 to version 27.0 of the .net library.  I upload an identification file to verify the account opener.  I upgraded and made all the changes to the code but am now receiving the below exception when I upload the file.  I did go back to version 26.0 and verified that it worked fine and the account was created with no additional requirements.  I'm using .net core 2.2, Visual Studio 2019 on a Windows 10 machine.  Here's the code I'm using.

```c#
StripeConfiguration.ApiKey=apiKey;
Stripe.File file = null;
if (System.IO.File.Exists(filename))
{
    using (FileStream stream = System.IO.File.Open(filename, FileMode.Open))
    {
        var service = new FileService();
        file = service.Create(
            new FileCreateOptions()
            {
                File = stream,
                Purpose = purpose
            }
        );
    }
}
```

Thanks for your help.
Bill

```
Stripe.StripeException
  HResult=0x80131500
  Message=Invalid UTF-8 characters found in POST body: "image/png".  For assistance, please contact support@stripe.com.
  Source=Stripe.net
  StackTrace:
   at Stripe.StripeClient.ProcessResponse[T](StripeResponse response)
   at Stripe.StripeClient.<RequestAsync>d__25`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stripe.Service`1.<RequestAsync>d__23`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stripe.Service`1.Request[T](HttpMethod method, String path, BaseOptions options, RequestOptions requestOptions)
   at Stripe.FileService.Create(FileCreateOptions options, RequestOptions requestOptions)
   at CommunityBuilder.BLL.Services.BAOStripeService.UploadFile(String filename, String purpose, String apiKey) in C:\Users\bill\source\repos\BuildAnOrgPlatform\CommunityBuilder.BLL\Services\BAOStripeService.cs:line 672
   at CommunityBuilder.BLL.Services.BAOStripeService.CreateTrialAccount(String name, String email, StripeAccountViewModel savm) in C:\Users\bill\source\repos\BuildAnOrgPlatform\CommunityBuilder.BLL\Services\BAOStripeService.cs:line 630
   at CommunityBuilder.BLL.Services.BillingService.CreateStripeTrialAccount(Int32 communityID, String name, String email) in C:\Users\bill\source\repos\BuildAnOrgPlatform\CommunityBuilder.BLL\Services\BillingService.cs:line 1658
   at CommunityBuilder.BLL.Services.MemberService.AddCommunity(AddCommunityViewModel acvm, String adminFirstName, String adminLastName, Int32 templateCommunity, Boolean platformCommunity) in C:\Users\bill\source\repos\BuildAnOrgPlatform\CommunityBuilder.BLL\Services\MemberService.cs:line 1202
   at CommunityBuilder.Controllers.AdminController.AddCommunity(AddCommunityViewModel acvm) in C:\Users\bill\source\repos\BuildAnOrgPlatform\CommunityBuilder\Controllers\AdminController.cs:line 165
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
```

**Comment by remi-stripe** [comment]
@bgecawichBAO Thanks for the report and sorry about the troubles here. I can also reproduce on my end so we're investigating and will push a fix once we found the issue.

**Comment by ob-stripe** [comment]
This should be fixed in version 27.1.1. Sorry for the inconvenience!

**Comment by bgecawichBAO** [comment]
Many thanks….I can confirm that this fixed my issue and I created a test account fully verified with 27.1.1.  I will continue testing.

Thank you for the quick turnaround!!!

Bill

**Comment by bgecawichBAO** [comment]
Thank you very much.
