### ISSUE TITLE
An error occurred while sending the request.

### ISSUE THREAD

**Issue by iriswu1031** [stripe/stripe-dotnet#1667]
OS version: Windows Server 2016
.NET version: 4.5
Stripe.net library version: 27.2.0

I am using the newest library version and trying to get details of a subscription.
However I failed to get the subscription using the SDK. Here is my code:

```
StripeConfiguration.ApiKey = StripeMgr.secretKey;

var SubscriptionService = new SubscriptionService();
var subscription = SubscriptionService.Get(session.SubscriptionId);
```

The error I got:

```
  System.Net.Http.HttpRequestException was unhandled by user code
  HResult=-2146233088
  Message=An error occurred while sending the request.
  Source=Stripe.net
  StackTrace:
       at Stripe.SystemNetHttpClient.<MakeRequestAsync>d__20.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
       at Stripe.StripeClient.<RequestAsync>d__25`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
       at Stripe.Service`1.<RequestAsync>d__23`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
       at Stripe.Service`1.Request[T](HttpMethod method, String path, BaseOptions options, RequestOptions requestOptions)
       at Stripe.Service`1.Request(HttpMethod method, String path, BaseOptions options, RequestOptions requestOptions)
       at Stripe.Service`1.GetEntity(String id, BaseOptions options, RequestOptions requestOptions)
       at Stripe.SubscriptionService.Get(String subscriptionId, SubscriptionGetOptions options, RequestOptions requestOptions)
       at WebControllers.StripeBaseController.DataFeed() in d:\Website\XXXXX\StripeBaseControllers.cs:line 130
       at lambda_method(Closure , ControllerBase , Object[] )
       at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
       at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
       at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.ActionInvocation.InvokeSynchronousActionMethod()
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
       at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
       at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
       at System.Web.Mvc.Async.AsyncResultWrapper.End[TResult](IAsyncResult asyncResult, Object tag)
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
  InnerException: System.Net.WebException
       HResult=-2146233079
       Message=The underlying connection was closed: An unexpected error occurred on a send.
       Source=System
       StackTrace:
            at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
            at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
       InnerException: System.IO.IOException
            HResult=-2146232800
            Message=Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
            Source=System
            StackTrace:
                 at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
                 at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
                 at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
            InnerException: System.Net.Sockets.SocketException
                 HResult=-2147467259
                 Message=An existing connection was forcibly closed by the remote host
                 Source=System
                 ErrorCode=10054
                 NativeErrorCode=10054
                 StackTrace:
                      at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
                      at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
                 InnerException: 
```

**Comment by chris-486** [comment]
Similar issue when creating a checkout session.

Works fine in a brand new project.    But same code is failing with the connection being closed in an existing project.

**Comment by remi-stripe** [comment]
@chris-486 Would you be able to give us a bit more details about this error? For example what is the id of the subscription you are trying to retrieve? I'd like to see if we can find those request on Stripe's side.

**Comment by iriswu1031** [comment]
> @chris-486 Would you be able to give us a bit more details about this error? For example what is the id of the subscription you are trying to retrieve? I'd like to see if we can find those request on Stripe's side.

I am trying to get subscription: sub_FGhwCiyWVFCIL3

**Comment by iriswu1031** [comment]
Not only subscription not working, I couldn't do anything using the new SDK.
I couldn't get invoice / create webhook etc. The error occurs everytime when I use the SDK to connect to stripe API.

**Comment by remi-stripe** [comment]
Thanks. I don't see any request coming in on our side to fetch that Subscription so it does look like the request is never making it to our servers at least. 

Looking into it further, I also don't see any request at all on this account inn the past 7 days. Not even with the older version of the library. 

Are you sure you're testing both versions on the same account? If so, could you give me an example Session id or Subscription id that you successfully created or retrieved with stripe-dotnet?

**Comment by iriswu1031** [comment]
I previously use the below code with different stripe account and it works fine.
The old stripe account use stripe.net version 25.13.0 and API version 2019-03-14.
Subscription id I successfully got using the old account: sub_EzYy9CQzt4g1hQ

```
StripeConfiguration.SetApiKey(StripeMgr.secretKey);

var SubscriptionService = new SubscriptionService();
var subscription = SubscriptionService.Get(session.SubscriptionId);
```

Later I created a new account, and the default API version is 2019-05-16.
Since Stripe.net version 25.13.0 does not support this new API version, I updated the package to version 27.2.0 and changed the method to set the API key. Then this error occurred.

```
StripeConfiguration.ApiKey = StripeMgr.secretKey;

var SubscriptionService = new SubscriptionService();
var subscription = SubscriptionService.Get(session.SubscriptionId);
```

**Comment by ob-stripe** [comment]
@iriswu1031 Can you try adding the following to your code, before sending any request to Stripe (e.g. immediately before or after setting the API key):

```c#
using System.Net;

ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12
```

and report here if you still observe the issue?

**Comment by iriswu1031** [comment]
> @iriswu1031 Can you try adding the following to your code, before sending any request to Stripe (e.g. immediately before or after setting the API key):
> 
> ```cs
> using System.Net;
> 
> ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12
> ```
> 
> and report here if you still observe the issue?

It works now! Thank you!

**Comment by ob-stripe** [comment]
Thanks for confirming! And sorry for the inconvenience, the library should do this automatically for you. We'll publish an update soon so you don't have to do this manually.

**Comment by ob-stripe** [comment]
This should be fixed in Stripe.net 27.3.1, which will appear on NuGet soon.

**Comment by lreidsai** [comment]
This fixed my (similar) issue as well. @ob-stripe , thanks for posting!

**Comment by jjspierx** [comment]
I just ran across this problem and found this issue #1667 by searching for the error.  The fix above worked for me, and my application targets .NET Framework 4.5 and the Stripe.net version I am using is the latest, v34.22.0.  It strangely only happens on my AWS EC2 server.  My home localhost can make Stripe API requests just fine without adding `ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12`  I know this issue is closed, but thought it might be worth looking into if something happened recently which broke this fix.

**Comment by ob-stripe** [comment]
@jjspierx Thanks for the report. The fix is still present in v34.22.0: https://github.com/stripe/stripe-dotnet/blob/v34.22.0/src/Stripe.net/Infrastructure/Public/SystemNetHttpClient.cs#L69-L73. Are you maybe using a custom client in place of `Stripe.SystemNetHttpClient`?

**Comment by jjspierx** [comment]
@ob-stripe I don't explicitly use Stripe.SystenNetHttpClient anywhere, I use the service classes, for instance, `ChargeService()` with no argument (`IStripeClient`).

**Comment by ob-stripe** [comment]
@jjspierx Strange. I don't know offhand what could be causing this. Would you mind opening a new issue and provide as much information as you can about your environment? (OS, .NET target version, full stacktrace, etc.)

**Comment by jjspierx** [comment]
Created new issue with details: [https://github.com/stripe/stripe-dotnet/issues/1922](url)
