### ISSUE TITLE
List credit notes error

### ISSUE THREAD

**Issue by realnickivanov** [stripe/stripe-dotnet#1782]
OS: Windows Server 2012 R2 Standard 64bit
.Net: 4.6.1
Stripe.Net: 27.24.0.0

Running the following code
```
var iteration = await _stripeCreditNoteService.ListAsync(new CreditNoteListOptions
{
    CustomerId = stripeCustomerId,
    Limit = 100,
    StartingAfter = startingAfter
});
```
I get the following exeption
```
Stripe.StripeException: Invalid response object from API: "{
  "object": "list",
  "data": [
    {
      "id": "cn_1F45mVH8CGtPy8T0TXecJF4H",
      "object": "credit_note",
      "amount": 100,
      "created": 1565009959,
      "currency": "eur",
      "customer": "cus_FZE647sLbykyuz",
      "customer_balance_transaction": null,
      "invoice": "in_1F45dzH8CGtPy8T0sNFR5YGW",
      "livemode": false,
      "memo": "Test",
      "metadata": {
      },
      "number": "U6FITOAI-0001-CN-01",
      "pdf": "https://pay.stripe.com/credit_notes/*************/***********/pdf",
      "reason": "duplicate",
      "refund": "re_1F45mVH8CGtPy8T0ZSO8OQBt",
      "status": "issued",
      "type": "post_payment",
      "voided_at": null
    }
  ],
  "has_more": false,
  "url": "/v1/credit_notes"
}
"
   at Stripe.StripeClient.ProcessResponse[T](StripeResponse response)
   at Stripe.StripeClient.<RequestAsync>d__25`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Stripe.Service`1.<RequestAsync>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

For example see request req_7dEJlJX9faTa9F 

I also tried Stripe.Net 27.25.1. Same error.

**Comment by remi-stripe** [comment]
@realnickivanov Thanks a lot for the report, I can reproduce so I'm going to investigate and then work on a fix.
