### ISSUE TITLE
Exception when source is null for a charge

### ISSUE THREAD

**Issue by di97mni** [stripe/stripe-dotnet#1816]
`Stripe.net.12.0.0\lib\net45\Stripe.net.dll`
`.NET 4.6.1`
`StripeApiVersion "2017-12-14"`

Getting this error when parsing this webhook for a `charge.succeeded` event

```
Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Null. Path 'source', line 84, position 16.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Stripe.Infrastructure.SourceConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
```

```
var stripeEvent = stripeEventConstructor.ConstructEvent(eventJson, stripeSignature);
StripeCharge charge;
switch (stripeEvent.Type)
{
    case StripeEvents.ChargeSucceeded:
        var version = StripeConfiguration.StripeApiVersion; // => "2017-12-14"
        //below line throws the exception
        charge = StripeEventUtility.ParseEventDataItem<StripeCharge>(stripeEvent.Data.Object)
...
```

Event
```json
{
	"id": "REMOVED",
	"object": "event",
	"api_version": "2017-12-14",
	"created": 1571322438,
	"data": {
		"object": {
			"id": "REMOVED",
			"object": "charge",
			"amount": 119500,
			"amount_refunded": 0,
			"application": null,
			"application_fee": null,
			"application_fee_amount": null,
			"balance_transaction": "REMOVED",
			"billing_details": {
				"address": {
					"city": null,
					"country": null,
					"line1": null,
					"line2": null,
					"postal_code": null,
					"state": null
				},
				"email": null,
				"name": null,
				"phone": null
			},
			"captured": true,
			"created": 1571322436,
			"currency": "sek",
			"customer": null,
			"description": "REMOVED",
			"destination": null,
			"dispute": null,
			"failure_code": null,
			"failure_message": null,
			"fraud_details": {
			},
			"invoice": null,
			"livemode": true,
			"metadata": {
				"order_id": "REMOVED"
			},
			"on_behalf_of": null,
			"order": null,
			"outcome": {
				"network_status": "approved_by_network",
				"reason": null,
				"risk_level": "normal",
				"seller_message": "Payment complete.",
				"type": "authorized"
			},
			"paid": true,
			"payment_intent": "REMOVED",
			"payment_method": "REMOVED",
			"payment_method_details": {
				"card": {
					"brand": "mastercard",
					"checks": {
						"address_line1_check": null,
						"address_postal_code_check": null,
						"cvc_check": "pass"
					},
					"country": "SE",
					"exp_month": 2,
					"exp_year": 2023,
					"fingerprint": "REMOVED",
					"funding": "credit",
					"installments": null,
					"last4": "REMOVED",
					"network": "mastercard",
					"three_d_secure": null,
					"wallet": null
				},
				"type": "card"
			},
			"receipt_email": null,
			"receipt_number": null,
			"receipt_url": "REMOVED",
			"refunded": false,
			"refunds": {
				"object": "list",
				"data": [

				],
				"has_more": false,
				"total_count": 0,
				"url": "REMOVED"
			},
			"review": null,
			"shipping": null,
			"source": null,
			"source_transfer": null,
			"statement_descriptor": null,
			"statement_descriptor_suffix": null,
			"status": "succeeded",
			"transfer_data": null,
			"transfer_group": null
		}
	},
	"livemode": true,
	"pending_webhooks": 1,
	"request": {
		"id": "REMOVED",
		"idempotency_key": null
	},
	"type": "charge.succeeded"
}
```

**Comment by remi-stripe** [comment]
@di97mni Usually this happens when the Charge was created by a `PaymentIntent` and using a `PaymentMethod` (or at least the `payment_method` field. In that case, `source` is null. Some older versions of stripe-dotnet did not support `source` to be nullable causing this crash.

What we recommend here is to upgrade stripe-dotnet to a more recent version, though there have been quite a lot of major changes since the version you were on.

**Comment by di97mni** [comment]
OK. Will upgrade the lib
