### ISSUE TITLE
NullReferenceException when parsing subscription deleted event

### ISSUE THREAD

**Issue by karisN** [stripe/stripe-dotnet#2068]
The parser fails for customer.subscription.deleted event, the same line of code works fine with checkout.session.completed event

`var stripeEvent = EventUtility.ParseEvent(json);`

```
Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Stripe.Infrastructure.EventConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Stripe.Infrastructure.JsonUtils.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Stripe.Infrastructure.JsonUtils.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Stripe.EventUtility.ParseEvent(String json, Boolean throwOnApiVersionMismatch)
```

**Comment by karisN** [comment]
@remi-stripe Originally 37.4.0, updated to 37.9.0 just now and still seeing the NullReference issue
This is the JSON I copied from the dashboard and use for testing.
```
{
  "object": {
    "id": "sub_HRAmHRV7jIu9iw",
    "object": "subscription",
    "application_fee_percent": null,
    "billing_cycle_anchor": 1591751352,
    "billing_thresholds": null,
    "cancel_at": null,
    "cancel_at_period_end": false,
    "canceled_at": 1591752148,
    "collection_method": "charge_automatically",
    "created": 1591751352,
    "current_period_end": 1594343352,
    "current_period_start": 1591751352,
    "customer": "cus_HRAmwJGbWHiSJW",
    "days_until_due": null,
    "default_payment_method": "pm_1GsIRHChjkvcuK9bearPQA1Q",
    "default_source": null,
    "default_tax_rates": [
    ],
    "discount": null,
    "ended_at": 1591752148,
    "items": {
      "object": "list",
      "data": [
        {
          "id": "si_HRAmuBKAOf3UiY",
          "object": "subscription_item",
          "billing_thresholds": null,
          "created": 1591751353,
          "metadata": {
          },
          "plan": {
            "id": "price_1GrxmGChjkvcuK9btQk63mwT",
            "object": "plan",
            "active": true,
            "aggregate_usage": null,
            "amount": 100,
            "amount_decimal": "100",
            "billing_scheme": "per_unit",
            "created": 1591671928,
            "currency": "usd",
            "interval": "month",
            "interval_count": 1,
            "livemode": false,
            "metadata": {
            },
            "nickname": null,
            "product": "prod_HQocAdAMBsNgNc",
            "tiers": null,
            "tiers_mode": null,
            "transform_usage": null,
            "trial_period_days": null,
            "usage_type": "licensed"
          },
          "price": {
            "id": "price_1GrxmGChjkvcuK9btQk63mwT",
            "object": "price",
            "active": true,
            "billing_scheme": "per_unit",
            "created": 1591671928,
            "currency": "usd",
            "livemode": false,
            "lookup_key": null,
            "metadata": {
            },
            "nickname": null,
            "product": "prod_HQocAdAMBsNgNc",
            "recurring": {
              "aggregate_usage": null,
              "interval": "month",
              "interval_count": 1,
              "trial_period_days": null,
              "usage_type": "licensed"
            },
            "tiers_mode": null,
            "transform_quantity": null,
            "type": "recurring",
            "unit_amount": 100,
            "unit_amount_decimal": "100"
          },
          "quantity": 1,
          "subscription": "sub_HRAmHRV7jIu9iw",
          "tax_rates": [
          ]
        }
      ],
      "has_more": false,
      "total_count": 1,
      "url": "/v1/subscription_items?subscription=sub_HRAmHRV7jIu9iw"
    },
    "latest_invoice": "in_1GsIRIChjkvcuK9b6bnq0E76",
    "livemode": false,
    "metadata": {
    },
    "next_pending_invoice_item_invoice": null,
    "pause_collection": null,
    "pending_invoice_item_interval": null,
    "pending_setup_intent": null,
    "pending_update": null,
    "plan": {
      "id": "price_1GrxmGChjkvcuK9btQk63mwT",
      "object": "plan",
      "active": true,
      "aggregate_usage": null,
      "amount": 100,
      "amount_decimal": "100",
      "billing_scheme": "per_unit",
      "created": 1591671928,
      "currency": "usd",
      "interval": "month",
      "interval_count": 1,
      "livemode": false,
      "metadata": {
      },
      "nickname": null,
      "product": "prod_HQocAdAMBsNgNc",
      "tiers": null,
      "tiers_mode": null,
      "transform_usage": null,
      "trial_period_days": null,
      "usage_type": "licensed"
    },
    "quantity": 1,
    "schedule": null,
    "start_date": 1591751352,
    "status": "canceled",
    "tax_percent": null,
    "transfer_data": null,
    "trial_end": null,
    "trial_start": null
  }
}
```

**Comment by remi-stripe** [comment]
@karisN I'm sorry, I'm getting confused about what you are trying to do. The raw JSON you mentioned is just a Subscription object, it's not an Event. Are you putting the raw JSON inside the `data` hash in a fake event? Would you be able to provide more specific code to reproduce the issue?

**Comment by remi-stripe** [comment]
For example, here's a simple dotnet code that deserializes an event JSON but putting your Subscription's JSON in the `data` part:

```
var json = "{ 'id': 'evt_123', 'object': 'event', 'api_version': '2020-03-02', 'created': 1567082240, 'data': { 'object': {  'id': 'sub_HRAmHRV7jIu9iw',  'object': 'subscription',  'application_fee_percent': null,  'billing_cycle_anchor': 1591751352,  'billing_thresholds': null,  'cancel_at': null,  'cancel_at_period_end': false,  'canceled_at': 1591752148,  'collection_method': 'charge_automatically',  'created': 1591751352,  'current_period_end': 1594343352,  'current_period_start': 1591751352,  'customer': 'cus_HRAmwJGbWHiSJW',  'days_until_due': null,  'default_payment_method': 'pm_1GsIRHChjkvcuK9bearPQA1Q',  'default_source': null,  'default_tax_rates': [  ],  'discount': null,  'ended_at': 1591752148,  'items': {    'object': 'list',    'data': [      {        'id': 'si_HRAmuBKAOf3UiY',        'object': 'subscription_item',        'billing_thresholds': null,        'created': 1591751353,        'metadata': {        },        'plan': {          'id': 'price_1GrxmGChjkvcuK9btQk63mwT',          'object': 'plan',          'active': true,          'aggregate_usage': null,          'amount': 100,          'amount_decimal': '100',          'billing_scheme': 'per_unit',          'created': 1591671928,          'currency': 'usd',          'interval': 'month',          'interval_count': 1,          'livemode': false,          'metadata': {          },          'nickname': null,          'product': 'prod_HQocAdAMBsNgNc',          'tiers': null,          'tiers_mode': null,          'transform_usage': null,          'trial_period_days': null,          'usage_type': 'licensed'        },        'price': {          'id': 'price_1GrxmGChjkvcuK9btQk63mwT',          'object': 'price',          'active': true,          'billing_scheme': 'per_unit',          'created': 1591671928,          'currency': 'usd',          'livemode': false,          'lookup_key': null,          'metadata': {          },          'nickname': null,          'product': 'prod_HQocAdAMBsNgNc',          'recurring': {            'aggregate_usage': null,            'interval': 'month',            'interval_count': 1,            'trial_period_days': null,            'usage_type': 'licensed'          },          'tiers_mode': null,          'transform_quantity': null,          'type': 'recurring',          'unit_amount': 100,          'unit_amount_decimal': '100'        },        'quantity': 1,        'subscription': 'sub_HRAmHRV7jIu9iw',        'tax_rates': [        ]      }    ],    'has_more': false,    'total_count': 1,    'url': '/v1/subscription_items?subscription=sub_HRAmHRV7jIu9iw'  },  'latest_invoice': 'in_1GsIRIChjkvcuK9b6bnq0E76',  'livemode': false,  'metadata': {  },  'next_pending_invoice_item_invoice': null,  'pause_collection': null,  'pending_invoice_item_interval': null,  'pending_setup_intent': null,  'pending_update': null,  'plan': {    'id': 'price_1GrxmGChjkvcuK9btQk63mwT',    'object': 'plan',    'active': true,    'aggregate_usage': null,    'amount': 100,    'amount_decimal': '100',    'billing_scheme': 'per_unit',    'created': 1591671928,    'currency': 'usd',    'interval': 'month',    'interval_count': 1,    'livemode': false,    'metadata': {    },    'nickname': null,    'product': 'prod_HQocAdAMBsNgNc',    'tiers': null,    'tiers_mode': null,    'transform_usage': null,    'trial_period_days': null,    'usage_type': 'licensed'  },  'quantity': 1,  'schedule': null,  'start_date': 1591751352,  'status': 'canceled',  'tax_percent': null,  'transfer_data': null,  'trial_end': null,  'trial_start': null}}, 'livemode': false, 'pending_webhooks': 1, 'request': { 'id': null, 'idempotency_key': 'idempotent' }, 'type': 'charge.succeeded' }";
var stripeEvent = EventUtility.ParseEvent(json, true);
```

This deserializes successfully for me

**Comment by karisN** [comment]
I resent the event and it seems to go through now. Not sure what happened, but thanks!!
