### ISSUE TITLE
Exception thrown parsing Dispute Events (webhooks) when Stripe API returns -1 for unix datetime on evidence_details.due_by

### ISSUE THREAD

**Issue by Hazzamanic** [stripe/stripe-dotnet#2628]
### Describe the bug

The Stripe API is returning -1 for `data.object.evidence_details.due_by`, which the SDK cannot parse and it throws an exception while parsing the JSON (exception included below). 

We are also seeing this exception when retrieving payment intents via the API, same property throwing, path: `charges.data[].dispute.evidence_details.due_by`.

Stripe support confirmed to us that -1 is a valid value for this field on Disputes (`evidence_details.due_by`) so the bug resides in how the SDK is handling this unix datetime value.

This is currently preventing us handling some disputes in our webhooks.

### To Reproduce

Use `Stripe.EventUtility.ParseEvent` to parse a dispute Event where `data.object.evidence_details.due_by` is set to -1. 

### Expected behavior

SDK to parse -1 as a null datetime

### OS

Windows

### .NET version

.net 6.0

### Library version

Stripe.net 39.110.0

### API version

2020-08-27

### Additional context

Exception thrown by SDK:

```
Newtonsoft.Json.JsonSerializationException: Cannot convert value that is before Unix epoch of 00:00:00 UTC on 1 January 1970 to System.Nullable`1[System.DateTime].
   at Stripe.Infrastructure.UnixDateTimeConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Stripe.Infrastructure.StripeObjectConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Stripe.Infrastructure.EventConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Stripe.Infrastructure.JsonUtils.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Stripe.EventUtility.ParseEvent(String json, Boolean throwOnApiVersionMismatch)
   at ...
```

**Comment by IanKemp** [comment]
A couple of further questions/considerations around this:

* Does/should the same logic (-1 == `default(DateTime?`) apply to all properties typed as `DateTime?` in the SDK, not just this one?
* The Stripe API docs make no differentiation between a timestamp and a nullable timestamp (e.g. [for this field](https://stripe.com/docs/api/disputes/object#dispute_object-evidence_details-due_by)) but this SDK does make that distinction. Should the API docs be updated to make the same distinction?

**Comment by anniel-stripe** [comment]
Hello, thanks so much for submitting this issue! I've brought this up internally and this appears to be a bug in the case of [unchallengeable disputes](https://stripe.com/docs/disputes/how-disputes-work#unchallengeable-disputes). We're working on fixing this in the API - I'll keep this issue open and update it when it's resolved in the API.

**Comment by anniel-stripe** [comment]
To answer @IanKemp 's first question, this is a bug with the Disputes API so it should not apply to other `DateTime` properties.

For the second question, adding nullable type information is definitely a top ask that would improve our API docs, and is on our radar. Unfortunately, until that is added to the docs, I'll have to point you to our [OpenAPI spec](https://github.com/stripe/openapi) as a source of truth for that information.

**Comment by IanKemp** [comment]
@anniel-stripe Thanks for the prompt feedback; do you have a guesstimate for when we can expect a new .NET SDK version with this fix? And, would this version include the breaking changes released on 2022-11-15 (i.e. requiring code changes for our end) or would it contain only the fix? For obvious reasons we'd very much prefer the latter.

**Comment by anniel-stripe** [comment]
Hi @IanKemp , our proposed fix would be a change to the API itself to make it return `0` where it previously returned `-1`, so it shouldn't require upgrading to a new version of the SDK. This fix would apply to all API versions, so you would not need to upgrade your API Version.

Our current estimate to start rolling out this change would be by the end of next week. Thank you for your patience as we fix this bug!

**Comment by anniel-stripe** [comment]
Update: This change is being rolled out, and the API should return `0` instead of `-1` now. Can you check if the SDK still throws the same error?

**Comment by anniel-stripe** [comment]
OK apologies for the extra notifications, but this change should be active now. Can you check if the SDK still throws this error?

**Comment by Hazzamanic** [comment]
Apologies for the delay getting back to you @anniel-stripe. Yes this looks all good in the API now, thank you for helping us get this sorted!
