### ISSUE TITLE
Embedded Checkout Debug Errors

### ISSUE THREAD

**Issue by afnan** [stripe/stripe-dotnet#2958]
### Describe the bug

I have implemented embedded checkout in a blazor .NET 8 app. The checkout renders fine but after around 10 seconds it throws exceptions `newassets.hcaptca.com/......` js. 
this throws exception only during debugging mode and not otherwise. 

```

TypeError: Failed to execute 'load' on 'FontFace': Illegal invocation
Stack trace:
 >  at https://newassets.hcaptcha.com/c/d531f260d9c65e5a75a5e87eb6c8a9e980fbbd144124ede1c9c2333c635c7b9a/hsw.js:1:17195
 >    at kA (https://newassets.hcaptcha.com/c/d531f260d9c65e5a75a5e87eb6c8a9e980fbbd144124ede1c9c2333c635c7b9a/hsw.js:1:16472)
 >    at https://newassets.hcaptcha.com/c/d531f260d9c65e5a75a5e87eb6c8a9e980fbbd144124ede1c9c2333c635c7b9a/hsw.js:1:17164
 >    at https://newassets.hcaptcha.com/c/d531f260d9c65e5a75a5e87eb6c8a9e980fbbd144124ede1c9c2333c635c7b9a/hsw.js:1:17736
 >    at Array.reduce (<anonymous>)
 >    at yA (https://newassets.hcaptcha.com/c/d531f260d9c65e5a75a5e87eb6c8a9e980fbbd144124ede1c9c2333c635c7b9a/hsw.js:1:16795)
 >    at https://newassets.hcaptcha.com/c/d531f260d9c65e5a75a5e87eb6c8a9e980fbbd144124ede1c9c2333c635c7b9a/hsw.js:1:18363
 >    at https://newassets.hcaptcha.com/c/d531f260d9c65e5a75a5e87eb6c8a9e980fbbd144124ede1c9c2333c635c7b9a/hsw.js:1:9937
 >    at https://newassets.hcaptcha.com/c/d531f260d9c65e5a75a5e87eb6c8a9e980fbbd144124ede1c9c2333c635c7b9a/hsw.js:1:73119
 >    at Array.map (<anonymous>)
Error: Empty challenge
Stack trace:
 >  at S (https://newassets.hcaptcha.com/c/d531f260d9c65e5a75a5e87eb6c8a9e980fbbd144124ede1c9c2333c635c7b9a/hsw.js:1:10037)
 >    at https://newassets.hcaptcha.com/c/d531f260d9c65e5a75a5e87eb6c8a9e980fbbd144124ede1c9c2333c635c7b9a/hsw.js:1:71675
 >    at https://newassets.hcaptcha.com/c/d531f260d9c65e5a75a5e87eb6c8a9e980fbbd144124ede1c9c2333c635c7b9a/hsw.js:1:8968
 >    at Object.next (https://newassets.hcaptcha.com/c/d531f260d9c65e5a75a5e87eb6c8a9e980fbbd144124ede1c9c2333c635c7b9a/hsw.js:1:9086)
 >    at https://newassets.hcaptcha.com/c/d531f260d9c65e5a75a5e87eb6c8a9e980fbbd144124ede1c9c2333c635c7b9a/hsw.js:1:7890
 >    at new Promise (<anonymous>)
 >    at H (https://newassets.hcaptcha.com/c/d531f260d9c65e5a75a5e87eb6c8a9e980fbbd144124ede1c9c2333c635c7b9a/hsw.js:1:7612)
 >    at https://newassets.hcaptcha.com/c/d531f260d9c65e5a75a5e87eb6c8a9e980fbbd144124ede1c9c2333c635c7b9a/hsw.js:1:71485
 >    at https://newassets.hcaptcha.com/c/d531f260d9c65e5a75a5e87eb6c8a9e980fbbd144124ede1c9c2333c635c7b9a/hsw.js:1:9937
 >    at https://newassets.hcaptcha.com/c/d531f260d9c65e5a75a5e87eb6c8a9e980fbbd144124ede1c9c2333c635c7b9a/hsw.js:1:73119
NetworkError: A network error occurred.

```

### To Reproduce

Setup Embedded checkout in Blazor application

### Expected behavior

Display checkout and not show exceptions

### OS

Windows

### .NET version

8

### Library version

Stripe.net 45.10.0

### API version

Latest

**Comment by remi-stripe** [comment]
@afnan Github issues are limited to bug with the stripe-dotnet SDK itself. Your questions are about Embedded Checkout client-side and are more an integration support question. Please work directly with our support team for 1:1 help: <https://support.stripe.com/contact>

**Comment by lhill0714** [comment]
I have the same issue .net 8 blazor wasm. Working with stripe support but they seem to think this is on the client side. Any resolution yet? My browser debugging says there is an "Empty Challenge" causing the issue.

StackTrace:
  at t (https://newassets.hcaptcha.com/c/5b8e65083fb03d69f7f1c7f37b70a61765f316bdd0f1f53ab286361d1bc32723/hsw.js:1:10066)
